import 'Meal.dart';
import 'restaurant.dart';

var DUMMY_restaurants = [
  Restaurant(
    isFavorite: false,
    id: 'c1',
    title: 'Pizza Nina',
    location: "Amman-Jordan",
    rate: 2.9,
    affordability: Affordability.$,
    imageUrl: "Images/Restaurants_pics/Restaurant1.jpg",
    restaurantType: RestaurantType.Italian,
    fastestDelivery: false,
    hotOffers: true,
    nearMe: false,
  ),
  Restaurant(
    isFavorite: false,
    id: 'c2',
    title: 'Gusto Italian',
    location: "Amman-Jordan",
    rate: 4.4,
    affordability: Affordability.$,
    imageUrl: "Images/Restaurants_pics/Restaurant2.jpg",
    restaurantType: RestaurantType.Italian,
    fastestDelivery: true,
    hotOffers: false,
    nearMe: true,
  ),
  Restaurant(
    isFavorite: true,
    id: 'c3',
    title: 'FireFly',
    location: "Amman-Jordan",
    rate: 4.2,
    affordability: Affordability.$,
    imageUrl: "Images/Restaurants_pics/Restaurant3.jpg",
    restaurantType: RestaurantType.Smoke_House,
    fastestDelivery: true,
    hotOffers: false,
    nearMe: false,
  ),
  Restaurant(
    isFavorite: false,
    id: 'c4',
    title: 'Fakhr el-Din',
    location: "Amman-Jordan",
    rate: 2.6,
    affordability: Affordability.$,
    imageUrl: "Images/Restaurants_pics/Restaurant4.jpg",
    restaurantType: RestaurantType.Traditional,
    fastestDelivery: false,
    hotOffers: true,
    nearMe: true,
  ),
  Restaurant(
    isFavorite: true,
    id: 'c5',
    title: 'Hashem',
    location: "Amman-Jordan",
    rate: 3.8,
    affordability: Affordability.$,
    imageUrl: "Images/Restaurants_pics/Restaurant5.jpg",
    restaurantType: RestaurantType.Traditional,
    fastestDelivery: false,
    hotOffers: true,
    nearMe: false,
  ),
  Restaurant(
    isFavorite: true,
    id: 'c6',
    title: 'Kan Zaman',
    location: "Amman-Jordan",
    rate: 4.8,
    affordability: Affordability.$,
    imageUrl: "Images/Restaurants_pics/Restaurant6.jpg",
    restaurantType: RestaurantType.Traditional,
    fastestDelivery: true,
    hotOffers: false,
    nearMe: true,
  ),
  Restaurant(
    isFavorite: false,
    id: 'c7',
    title: 'Bab al-Yeman',
    location: "Amman-Jordan",
    rate: 4.6,
    affordability: Affordability.$,
    imageUrl: "Images/Restaurants_pics/Restaurant7.jpg",
    restaurantType: RestaurantType.Traditional,
    fastestDelivery: false,
    hotOffers: true,
    nearMe: true,
  ),
  Restaurant(
    isFavorite: true,
    id: 'c8',
    title: 'Rakwet Arab',
    location: "Amman-Jordan",
    rate: 2,
    affordability: Affordability.$,
    imageUrl: "Images/Restaurants_pics/Restaurant8.jpg",
    restaurantType: RestaurantType.Fast_Food,
    fastestDelivery: true,
    hotOffers: true,
    nearMe: true,
  ),
  Restaurant(
    isFavorite: false,
    id: 'c9',
    title: 'Ararat',
    location: "Amman-Jordan",
    rate: 3,
    affordability: Affordability.$,
    imageUrl: "Images/Restaurants_pics/Restaurant9.jpg",
    restaurantType: RestaurantType.Traditional,
    fastestDelivery: true,
    hotOffers: true,
    nearMe: true,
  ),
  Restaurant(
    isFavorite: false,
    id: 'c10',
    title: 'Brisket',
    location: "Amman-Jordan",
    rate: 4.9,
    affordability: Affordability.$,
    imageUrl: "Images/Restaurants_pics/Restaurant10.jpg",
    restaurantType: RestaurantType.Smoke_House,
    fastestDelivery: false,
    hotOffers: true,
    nearMe: false,
  ),
];

var DUMMY_MEALS = [
  Meal(
    id: 'm1',
    restaurantId: "c6",
    title: 'Tomato Sauce Spaghetti',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal1.jpg',
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    isInCart: false,
  ),
  Meal(
    id: 'm2',
    restaurantId: "c9",
    title: 'Pasta with Garlic',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal2.jpg',
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm3',
    restaurantId: "c4",
    title: 'Cream Of Tomato Soup',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal3.jpg',
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    isInCart: false,
  ),
  Meal(
    id: 'm4',
    restaurantId: "c5",
    title: 'Beef Carpaccio',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal4.jpeg',
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm5',
    restaurantId: "c1",
    title: 'Smoked Beef',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal5.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
    isInCart: false,
  ),
  Meal(
    id: 'm6',
    restaurantId: "c8",
    title: 'Ottoman Salad',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal6.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm7',
    restaurantId: "c2",
    title: 'Vegetable Tempura',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal7.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm8',
    restaurantId: "c10",
    title: 'Burrata',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal8.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    isInCart: true,
  ),
  Meal(
    id: 'm9',
    restaurantId: "c4",
    title: 'Family Party',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal9.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm10',
    restaurantId: "c6",
    title: 'Classic Burger Meal',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal10.jpg',
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    isInCart: false,
  ),
  /////////////////////////////
  ///
  Meal(
    id: 'm11',
    restaurantId: "c8",
    title: 'Tomato Sauce Spaghetti',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal1.jpg',
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    isInCart: false,
  ),
  Meal(
    id: 'm12',
    restaurantId: "c5",
    title: 'Pasta with Garlic',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal2.jpg',
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm13',
    restaurantId: "c10",
    title: 'Cream Of Tomato Soup',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal3.jpg',
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    isInCart: true,
  ),
  Meal(
    id: 'm14',
    restaurantId: "c9",
    title: 'Beef Carpaccio',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal4.jpeg',
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm15',
    restaurantId: "c2",
    title: 'Smoked Beef',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal5.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
    isInCart: false,
  ),
  Meal(
    id: 'm16',
    restaurantId: "c1",
    title: 'Ottoman Salad',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal6.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm17',
    restaurantId: "c5",
    title: 'Vegetable Tempura',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal7.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm18',
    restaurantId: "c3",
    title: 'Burrata',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal8.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    isInCart: false,
  ),
  Meal(
    id: 'm19',
    restaurantId: "c6",
    title: 'Family Party',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal9.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm20',
    restaurantId: "c8",
    title: 'Classic Burger Meal',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal10.jpg',
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    isInCart: false,
  ),

  /////
  ///
  /////////////////////////////////////
  Meal(
    id: 'm21',
    restaurantId: "c1",
    title: 'Tomato Sauce Spaghetti',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal1.jpg',
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    isInCart: false,
  ),
  Meal(
    id: 'm22',
    restaurantId: "c2",
    title: 'Pasta with Garlic',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal2.jpg',
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm23',
    restaurantId: "c3",
    title: 'Cream Of Tomato Soup',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal3.jpg',
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    isInCart: false,
  ),
  Meal(
    id: 'm24',
    restaurantId: "c4",
    title: 'Beef Carpaccio',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal4.jpeg',
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm25',
    restaurantId: "c5",
    title: 'Smoked Beef',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal5.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: true,
    isInCart: false,
  ),
  Meal(
    id: 'm26',
    restaurantId: "c6",
    title: 'Ottoman Salad',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal6.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm27',
    restaurantId: "c7",
    title: 'Vegetable Tempura',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal7.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm28',
    restaurantId: "c8",
    title: 'Burrata',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal8.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
    isInCart: false,
  ),
  Meal(
    id: 'm29',
    restaurantId: "c9",
    title: 'Family Party',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal9.jpg',
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: true,
    isLactoseFree: false,
    isInCart: false,
  ),
  Meal(
    id: 'm30',
    restaurantId: "c10",
    title: 'Classic Burger Meal',
    price: 5.99,
    description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut maximus mauris et ex laoreet, vitae pulvinar metus facilisis. Etiam suscipit maximus tellus, non sagittis augue pellentesque sit amet. Nulla facilisi. Vivamus faucibus scelerisque aliquet. Ut quis magna condimentum, varius erat id, tincidunt elit. Nunc nec scelerisque erat, in elementum leo.",
    imageUrl: 'Images/Meals_pics/Meal10.jpg',
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
    isInCart: false,
  ),
];
